spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS


#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: cors_route
#          uri: [7](https://example.org)
#          predicates:
#            - Path=/service/**
#              metadata:
#                cors:
#                  allowedOrigins: '*'
#                  allowedMethods: - GET - POST
#                  allowedHeaders: '*'
#                  maxAge: 30
